[package]
name = "proj"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.1.6"
serde = { version = "1.0.136", features = ["derive"] }
ndarray = "0.15"
linfa = { git = "https://github.com/rust-ml/linfa" }
linfa-linear = { git = "https://github.com/rust-ml/linfa" }
smartcore = {version = "0.2", features=["ndarray-bindings"]}
rand = "0.8"